export const GET_NEWARRIVAL = "GET_NEWARRIVAL";
export const GET_NEWARRIVAL_SUCCESS = "GET_NEWARRIVAL_SUCCESS";
export const GET_NEWARRIVAL_FAILURE = "GET_NEWARRIVAL_FAILURE";

export const GET_SHIRT = "GET_SHIRT";
export const GET_SHIRT_SUCCESS = "GET_SHIRT_SUCCESS";
export const GET_SHIRT_FAILURE = "GET_SHIRT_FAILURE";

export const GET_TSHIRT = "GET_TSHIRT";
export const GET_TSHIRT_SUCCESS = "GET_TSHIRT_SUCCESS";
export const GET_TSHIRT_FAILURE = "GET_TSHIRT_FAILURE";