
export const GET_SHIRT = "GET_SHIRT";
export const GET_SHIRT_SUCCESS = "GET_SHIRT_SUCCESS";
export const GET_SHIRT_FAILURE = "GET_SHIRT_FAILURE";

export const GET_TSHIRT = "GET_TSHIRT";
export const GET_TSHIRT_SUCCESS = "GET_TSHIRT_SUCCESS";
export const GET_TSHIRT_FAILURE = "GET_TSHIRT_FAILURE";

export const GET_TROUSER = "GET_TROUSER";
export const GET_TROUSER_SUCCESS = "GET_TROUSER_SUCCESS";
export const GET_TROUSER_FAILURE = "GET_TROUSER_FAILURE";

export const  DELETE_PRODUCT_CART_REQUEST = 'DELETE_PRODUCT_CART_REQUEST'
export const  DELETE_PRODUCT_CART_SUCCESS = 'DELETE_PRODUCT_CART_SUCCESS'
export const  DELETE_PRODUCT_CART_FAILURE = 'DELETE_PRODUCT_CART_FAILURE'

export const  ADD_PRODUCT_DETAILS_CART_REQUEST = 'ADD_PRODUCT_DETAILS_CART_REQUEST'
export const  ADD_PRODUCT_DETAILS_CART_SUCCESS = 'ADD_PRODUCT_DETAILS_CART_SUCCESS'
export const  ADD_PRODUCT_DETAILS_CART_FAILURE = 'ADD_PRODUCT_DETAILS_CART_FAILURE'



